import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	const [counter, setCounter] = useState(0);

	const incrementCounterHandler = () => {
		setCounter(counter++);
	};

	const decrementCounterHandler = () => {
		setCounter(counter--);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>This is a head title</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={styles.description}>
					The counter is
					<br />
					<code className={styles.code}>{counter}</code>
				</p>

				<div className={styles.grid}>
					<button className={styles.card} onClick={incrementCounterHandler}>
						<p>Increment</p>
					</button>

					<button className={styles.card} onClick={decrementCounterHandler}>
						<p>Decrement</p>
					</button>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
